set nocompatible
filetype off

"plugins
call plug#begin('~/.vim/bundle')

Plug 'airblade/vim-gitgutter'
Plug 'sjl/gundo.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'gregsexton/MatchTag'
Plug 'chrisbra/Recover.vim'
Plug 'scrooloose/nerdtree'
Plug 'mileszs/ack.vim'
Plug 'coot/atp_vim'
Plug 'VelkyVenik/vim-avr'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'othree/html5.vim'
Plug 'Mr-Pi/lagerLogSyntax'
"Plug 'MarcWeber/vim-addon-mw-utils'
"Plug 'tomtom/tlib_vim'
"Plug 'garbas/vim-snipmate'
"Plug 'honza/vim-snippets'
Plug 'ap/vim-css-color'
Plug 'hail2u/vim-css3-syntax'
Plug 'tpope/vim-eunuch'
Plug 'krisajenkins/vim-pipe'
Plug 'dhruvasagar/vim-table-mode'
"Plug 'lhzw/vim-table-mode'
Plug 'christoomey/vim-tmux-navigator'
Plug 'vim-erlang/vim-rebar'
Plug 'vim-erlang/vim-erlang-compiler'
Plug 'vim-erlang/vim-erlang-skeletons'
Plug 'vim-erlang/vim-erlang-runtime'
Plug 'vim-erlang/vim-erlang-omnicomplete'
Plug 'vim-erlang/vim-erlang-tags'
Plug 'vim-erlang/erlang-motions.vim'
Plug 'vim-erlang/vim-dialyzer'
Plug 'majutsushi/tagbar'
"Plug 'vim-scripts/taglist.vim'
"Plug 'Valloric/YouCompleteMe'
Plug 'scrooloose/syntastic'
Plug 'Raimondi/delimitMate'
Plug 'elzr/vim-json'
Plug 'vimwiki/vimwiki'
Plug '907th/vim-auto-save'
"Plug 'Yggdroot/indentLine'
Plug 'Mr-Pi/ferm.vim'
Plug 'pearofducks/ansible-vim'
Plug 'will133/vim-dirdiff'
Plug 'fatih/vim-go'
Plug 'godlygeek/tabular'
"Plug 'plasticboy/vim-markdown'
Plug 'python-mode/python-mode'
Plug 'davidhalter/jedi-vim'
Plug 'dahu/vim-help'
Plug 'posva/vim-vue'
Plug 'Glench/Vim-Jinja2-Syntax'
Plug 'leafgarland/typescript-vim'
Plug 'svjunic/RadicalGoodSpeed.vim'
Plug 'mhinz/vim-startify'
Plug 'uplus/vim-clang-rename'
Plug 'justmao945/vim-clang'
Plug 'mkitt/tabline.vim'
Plug 'Mr-Pi/git-blame.vim'
Plug 'rhysd/git-messenger.vim'
Plug 'pedrohdz/vim-yaml-folds'

call plug#end()
filetype plugin indent on

set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans=1
let g:solarized_contrast="high"
let g:solarized_visibility="high"
"let g:solarized_bold=1
"let g:solarized_underline=1
"let g:solarized_italic=1
colorscheme solarized
"colorscheme radicalgoodspeed
set number
set ignorecase
set incsearch
set nohlsearch
set wildmenu
set showcmd
set bs=2 "allow backspace in insert mode
set history=5000
set autoread "Set to auto read when a file is changed from the outside
set showmatch
set wrap
set encoding=utf-8
set foldenable
"set viminfo='100,\"1000,:100,%,n~/.vim/viminfo
set mouse=""
set cursorline
set laststatus=2
set ruler
set t_ZH=[3m
set t_ZR=[23m

"python
let g:jedi#use_splits_not_buffers = "bottom"
let g:jedi#show_call_signatures = "2"
let g:pymode_python = 'python3'
let g:pymode = 0
let g:pymode_trim_whitespaces = 1
let g:pymode_options = 1
let g:pymode_options_max_line_length = 80
let g:pymode_indent = 1
let g:pymode_lint_on_fly = 0
let g:pymode_rope = 1
let g:pymode_rope_lookup_project = 1
let g:pymode_rope_show_doc_bind = ',d'
let g:pymode_rope_autoimport = 1
let g:pymode_rope_goto_definition_bind = '<leader>g'
let g:pymode_run_bind = '<leader>c'
let g:pymode_rope_rename_bind = '<leader>r'
let g:pymode_rope_rename_module_bind = '<leader>mr'
let g:pymode_rope_module_to_package_bind = '<leader>mp'
let g:pymode_rope_show_doc_bind = '<leader>d'
let g:pymode_breakpoint_cmd = 'ipdb'

"show a undo tree (gundo)
nmap <S-U> :GundoToggle<CR>
let g:gundo_right = 1

"better undo (persitent history)
set undofile
set undodir=~/.vim/undodir

"better repeat command
nmap . .`[

"tab management
"hi TabLine      ctermfg=Black  ctermbg=LightGray     cterm=NONE
"hi TabLineFill  ctermfg=Black  ctermbg=LightGray     cterm=NONE
hi TabLineSel   ctermfg=Black  ctermbg=Green         cterm=NONE
set showtabline=2
nmap tc :tabnew<CR>
nmap tn :tabnext<CR>
nmap tf :tabfirst<CR>
nmap tp :tabprevious<CR>
nmap to :tabnew<CR>:NERDTree<CR>
nmap tC :tabclose<CR>

"split screen
nmap %vc :vsplit<CR>
nmap %hc :split<CR>
nmap %vn <C-w><C-w>

"Tagbar
nmap <F8> :TagbarToggle<CR>

"toggle line numbering and toggle show search result
nmap <F6> :set invnumber<CR>
nmap <C-n> :set invhlsearch<CR>

"F7 toggles NERDTree
nmap <F7> :NERDTreeToggle<CR>
"let NERDTreeQuitOnOpen=1

"text snippets
nmap %dd i<C-r>=strftime("%F")<CR>
nmap %dt i<C-r>=strftime("%T")<CR>

"spellcheck
nmap %sn :set spell spelllang=""<CR>
nmap %sd :set spell spelllang=de<CR>
nmap %se :set spell spelllang=en<CR>

"copy and past
"	x = X11 clipboard
"	s = system clipboard
map %cx "*y
map %cs "+y
map %cv y
map %xx "*x
map %xs "+x
map %xv x
nmap %px "*p
nmap %ps "+p
nmap %pv p
map <F9> "+
map <F10> "*
nmap <F9> "+
nmap <F10> "*
vmap <F9> "+
vmap <F10> "*

nmap ff <C-]>

"leader
let mapleader=","

"table mode (markdown-compatible)
let g:table_mode_corner="|"
let g:vim_markdown_folding_disabled = 1
let g:vim_markdown_folding_style_pythonic = 1
set conceallevel=2
let g:vim_markdown_no_extensions_in_markdown = 1
let g:vim_markdown_fenced_languages = ['yml=yaml']


"tmux integration
let g:tmux_navigator_save_on_switch=1
nmap <C-Left> :TmuxNavigateLeft<CR>
nmap <C-Down> :TmuxNavigateDown<CR>
nmap <C-Up> :TmuxNavigateUp<CR>
nmap <C-Right> :TmuxNavigateRight<CR>
nmap <F2> :TmuxNavigatePrevious<CR>
imap <C-Left> <ESC>:TmuxNavigateLeft<CR>a
imap <C-Down> <ESC>:TmuxNavigateDown<CR>a
imap <C-Up> <ESC>:TmuxNavigateUp<CR>a
imap <C-Right> <ESC>:TmuxNavigateRight<CR>a
imap <F2> <ESC>:TmuxNavigatePrevious<CR>a
nmap <C-S-Up> :res +1<CR>
nmap <C-S-Down> :res -1<CR>
nmap <C-S-Right> :vertical resize +1<CR>
nmap <C-S-Left> :vertical resize -1<CR>

"help panel at the right site
augroup helpfiles
	au!
	au BufRead,BufEnter */doc/* wincmd L
augroup END

"gzip
:augroup gzip
:  autocmd!
:  autocmd BufReadPre,FileReadPre	*.gz set bin
:  autocmd BufReadPost,FileReadPost	*.gz '[,']!gunzip
:  autocmd BufReadPost,FileReadPost	*.gz set nobin
:  autocmd BufReadPost,FileReadPost	*.gz execute ":doautocmd BufReadPost " . expand("%:r")
:  autocmd BufWritePost,FileWritePost	*.gz !mv <afile> <afile>:r
:  autocmd BufWritePost,FileWritePost	*.gz !gzip <afile>:r

:  autocmd FileAppendPre		*.gz !gunzip <afile>
:  autocmd FileAppendPre		*.gz !mv <afile>:r <afile>
:  autocmd FileAppendPost		*.gz !mv <afile> <afile>:r
:  autocmd FileAppendPost		*.gz !gzip <afile>:r
:augroup END

"VimWiki
let g:auto_toc = 1
let g:auto_tags = 1
let wiki1 = {}
let wiki1.path = '~/hg/stuvusIT/wiki/vim/'
let wiki1.path_html = '~/hg/stuvusIT/wiki/html'
let wiki1.auto_export = 1
let wiki1.auto_toc = 1
let wiki2 = {}
let wiki2.path = '~/hg/mitschrieb/'
let wiki2.path_html = '~/hg/mitschrieb/html/'
let wiki2.auto_export = 1
let wiki2.auto_toc = 1
let g:vimwiki_list = [wiki1, wiki2]
let g:custom_wiki2html = '/home/mrpi/Downloads/misaka_md2html.py'

"session and bla
let g:auto_save = 1
let g:startify_session_dir = '~/.vim/session'
let g:startify_session_autoload = 1
let g:startify_session_persistence = 1

"C,C++
let g:clang_c_options = '-std=c99'
autocmd FileType c,cpp nmap <buffer><silent>,lr <Plug>(clang_rename-current)

"misc
autocmd BufNewFile,BufRead /home/mrpi/hg/stuvus_config*/*.yml set sw=2
autocmd BufNewFile,BufRead /home/mrpi/hg/stuvus_config*/*/*.yml set sw=2
autocmd BufNewFile,BufRead /home/mrpi/hg/stuvus_config*/*/*/*.yml set sw=2
autocmd BufNewFile,BufRead /home/mrpi/hg/server/ansible/*.yml set sw=2
autocmd BufNewFile,BufRead /home/mrpi/hg/server/ansible/*/*.yml set sw=2
autocmd BufNewFile,BufRead /home/mrpi/hg/server/ansible/*/*/*.yml set sw=2
autocmd BufNewFile,BufRead /home/mrpi/hg/server/rapu/new/ansible/*.yml set sw=2
autocmd BufNewFile,BufRead /home/mrpi/hg/server/rapu/new/ansible/*/*.yml set sw=2
autocmd BufNewFile,BufRead /home/mrpi/hg/server/rapu/new/ansible/*/*/*.yml set sw=2

"git
let g:gitgutter_terminal_reports_focus = 0
let g:git_messenger_close_on_cursor_moved = v:false
let g:git_messenger_always_into_popup = v:true
nmap <DOWN> j:call gitblame#echo()<CR>
nmap <UP>   k:call gitblame#echo()<CR>
"nmap j      <DOWN>
"nmap k      <UP>
set shortmess+=O
